//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N19_restaurant_management_software
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietMonAn
    {
        public int idChiTiet { get; set; }
        public Nullable<int> idMonAn { get; set; }
        public Nullable<int> idNguyenLieu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string DonVi { get; set; }
    
        public virtual MonAn MonAn { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
