//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N19_restaurant_management_software
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatMon
    {
        public int idDatMon { get; set; }
        public Nullable<int> idBanAn { get; set; }
        public Nullable<int> idMonAn { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual BanAn BanAn { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
