//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N19_restaurant_management_software
{
    using System;
    using System.Collections.Generic;
    
    public partial class frm_NhanVien
    {
        public int ID { get; set; }
        public string Ho_ten { get; set; }
        public string Gioi_tinh { get; set; }
        public System.DateTime Ngay_sinh { get; set; }
        public string So_dien_thoai { get; set; }
        public string Dia_chi { get; set; }
        public string CMND { get; set; }
        public string Email { get; set; }
        public string Chuc_vu { get; set; }
        public System.DateTime Ngay_vao_lam { get; set; }
        public int Luong { get; set; }
    }
}
