//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N19_restaurant_management_software
{
    using System;
    using System.Collections.Generic;
    
    public partial class frm_DatMon
    {
        public int ID { get; set; }
        public string Ten_Mon_An { get; set; }
        public int Gia { get; set; }
        public Nullable<int> So_luong { get; set; }
        public string Ten_Khach_Hang { get; set; }
    }
}
