//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N19_restaurant_management_software
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int idHoaDon { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        public Nullable<int> Tien { get; set; }
        public Nullable<int> idKhuyenMai { get; set; }
        public string ThongTin { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
    }
}
