//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N19_restaurant_management_software
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class N19_QuanLyQuanAnEntities : DbContext
    {
        public N19_QuanLyQuanAnEntities()
            : base("name=N19_QuanLyQuanAnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BanAn> BanAns { get; set; }
        public virtual DbSet<ChiTietMonAn> ChiTietMonAns { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<DatHang> DatHangs { get; set; }
        public virtual DbSet<DatMon> DatMons { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
        public virtual DbSet<MonAn> MonAns { get; set; }
        public virtual DbSet<NguyenLieu> NguyenLieux { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<frm_BanAn> frm_BanAn { get; set; }
        public virtual DbSet<frm_CongThuc> frm_CongThuc { get; set; }
        public virtual DbSet<frm_DanhMuc> frm_DanhMuc { get; set; }
        public virtual DbSet<frm_DatMon> frm_DatMon { get; set; }
        public virtual DbSet<frm_DoanhThu> frm_DoanhThu { get; set; }
        public virtual DbSet<frm_KhachHang> frm_KhachHang { get; set; }
        public virtual DbSet<frm_KhoHang> frm_KhoHang { get; set; }
        public virtual DbSet<frm_MonAn> frm_MonAn { get; set; }
        public virtual DbSet<frm_NhanVien> frm_NhanVien { get; set; }
        public virtual DbSet<frm_TaiKhoan> frm_TaiKhoan { get; set; }
    
        [DbFunction("N19_QuanLyQuanAnEntities", "DSDoanhThuTrongKhoangTG")]
        public virtual IQueryable<DSDoanhThuTrongKhoangTG_Result> DSDoanhThuTrongKhoangTG(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DSDoanhThuTrongKhoangTG_Result>("[N19_QuanLyQuanAnEntities].[DSDoanhThuTrongKhoangTG](@FromDate, @ToDate)", fromDateParameter, toDateParameter);
        }
    
        [DbFunction("N19_QuanLyQuanAnEntities", "TimCongThuc")]
        public virtual IQueryable<TimCongThuc_Result> TimCongThuc(Nullable<int> idMonAn)
        {
            var idMonAnParameter = idMonAn.HasValue ?
                new ObjectParameter("idMonAn", idMonAn) :
                new ObjectParameter("idMonAn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TimCongThuc_Result>("[N19_QuanLyQuanAnEntities].[TimCongThuc](@idMonAn)", idMonAnParameter);
        }
    
        [DbFunction("N19_QuanLyQuanAnEntities", "TimDanhMuc")]
        public virtual IQueryable<TimDanhMuc_Result> TimDanhMuc(Nullable<int> tenDanhMuc)
        {
            var tenDanhMucParameter = tenDanhMuc.HasValue ?
                new ObjectParameter("TenDanhMuc", tenDanhMuc) :
                new ObjectParameter("TenDanhMuc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TimDanhMuc_Result>("[N19_QuanLyQuanAnEntities].[TimDanhMuc](@TenDanhMuc)", tenDanhMucParameter);
        }
    
        [DbFunction("N19_QuanLyQuanAnEntities", "TimDanhMucCuaMonAn")]
        public virtual IQueryable<TimDanhMucCuaMonAn_Result> TimDanhMucCuaMonAn(Nullable<int> idMonAn)
        {
            var idMonAnParameter = idMonAn.HasValue ?
                new ObjectParameter("idMonAn", idMonAn) :
                new ObjectParameter("idMonAn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TimDanhMucCuaMonAn_Result>("[N19_QuanLyQuanAnEntities].[TimDanhMucCuaMonAn](@idMonAn)", idMonAnParameter);
        }
    
        [DbFunction("N19_QuanLyQuanAnEntities", "TimKhachHang")]
        public virtual IQueryable<TimKhachHang_Result> TimKhachHang(Nullable<int> tenKhachHang)
        {
            var tenKhachHangParameter = tenKhachHang.HasValue ?
                new ObjectParameter("TenKhachHang", tenKhachHang) :
                new ObjectParameter("TenKhachHang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TimKhachHang_Result>("[N19_QuanLyQuanAnEntities].[TimKhachHang](@TenKhachHang)", tenKhachHangParameter);
        }
    
        [DbFunction("N19_QuanLyQuanAnEntities", "TimMonAn")]
        public virtual IQueryable<TimMonAn_Result> TimMonAn(Nullable<int> tenMonAn)
        {
            var tenMonAnParameter = tenMonAn.HasValue ?
                new ObjectParameter("TenMonAn", tenMonAn) :
                new ObjectParameter("TenMonAn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TimMonAn_Result>("[N19_QuanLyQuanAnEntities].[TimMonAn](@TenMonAn)", tenMonAnParameter);
        }
    
        [DbFunction("N19_QuanLyQuanAnEntities", "TimNguyenLieu")]
        public virtual IQueryable<TimNguyenLieu_Result> TimNguyenLieu(Nullable<int> tenNguyenLieu)
        {
            var tenNguyenLieuParameter = tenNguyenLieu.HasValue ?
                new ObjectParameter("TenNguyenLieu", tenNguyenLieu) :
                new ObjectParameter("TenNguyenLieu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TimNguyenLieu_Result>("[N19_QuanLyQuanAnEntities].[TimNguyenLieu](@TenNguyenLieu)", tenNguyenLieuParameter);
        }
    
        [DbFunction("N19_QuanLyQuanAnEntities", "TimNhanVien")]
        public virtual IQueryable<TimNhanVien_Result> TimNhanVien(Nullable<int> tenNhanVien)
        {
            var tenNhanVienParameter = tenNhanVien.HasValue ?
                new ObjectParameter("TenNhanVien", tenNhanVien) :
                new ObjectParameter("TenNhanVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TimNhanVien_Result>("[N19_QuanLyQuanAnEntities].[TimNhanVien](@TenNhanVien)", tenNhanVienParameter);
        }
    
        public virtual int sp_SuaBanAn(Nullable<int> idBanAn, Nullable<int> sttBan, Nullable<bool> trangThai)
        {
            var idBanAnParameter = idBanAn.HasValue ?
                new ObjectParameter("idBanAn", idBanAn) :
                new ObjectParameter("idBanAn", typeof(int));
    
            var sttBanParameter = sttBan.HasValue ?
                new ObjectParameter("sttBan", sttBan) :
                new ObjectParameter("sttBan", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("trangThai", trangThai) :
                new ObjectParameter("trangThai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaBanAn", idBanAnParameter, sttBanParameter, trangThaiParameter);
        }
    
        public virtual int sp_SuaChiTietMonAn(Nullable<int> idChiTiet, Nullable<int> idMonAn, Nullable<int> idNguyenLieu, Nullable<int> soLuong, string donVi)
        {
            var idChiTietParameter = idChiTiet.HasValue ?
                new ObjectParameter("idChiTiet", idChiTiet) :
                new ObjectParameter("idChiTiet", typeof(int));
    
            var idMonAnParameter = idMonAn.HasValue ?
                new ObjectParameter("idMonAn", idMonAn) :
                new ObjectParameter("idMonAn", typeof(int));
    
            var idNguyenLieuParameter = idNguyenLieu.HasValue ?
                new ObjectParameter("idNguyenLieu", idNguyenLieu) :
                new ObjectParameter("idNguyenLieu", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var donViParameter = donVi != null ?
                new ObjectParameter("DonVi", donVi) :
                new ObjectParameter("DonVi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaChiTietMonAn", idChiTietParameter, idMonAnParameter, idNguyenLieuParameter, soLuongParameter, donViParameter);
        }
    
        public virtual int sp_SuaDanhMuc(Nullable<int> idDanhMuc, string tenDanhMuc, string moTa)
        {
            var idDanhMucParameter = idDanhMuc.HasValue ?
                new ObjectParameter("idDanhMuc", idDanhMuc) :
                new ObjectParameter("idDanhMuc", typeof(int));
    
            var tenDanhMucParameter = tenDanhMuc != null ?
                new ObjectParameter("TenDanhMuc", tenDanhMuc) :
                new ObjectParameter("TenDanhMuc", typeof(string));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaDanhMuc", idDanhMucParameter, tenDanhMucParameter, moTaParameter);
        }
    
        public virtual int sp_SuaDatMon(Nullable<int> idDatMon, Nullable<int> idBanAn, Nullable<int> idMonAn, Nullable<int> idKhachHang, Nullable<int> soLuong)
        {
            var idDatMonParameter = idDatMon.HasValue ?
                new ObjectParameter("idDatMon", idDatMon) :
                new ObjectParameter("idDatMon", typeof(int));
    
            var idBanAnParameter = idBanAn.HasValue ?
                new ObjectParameter("idBanAn", idBanAn) :
                new ObjectParameter("idBanAn", typeof(int));
    
            var idMonAnParameter = idMonAn.HasValue ?
                new ObjectParameter("idMonAn", idMonAn) :
                new ObjectParameter("idMonAn", typeof(int));
    
            var idKhachHangParameter = idKhachHang.HasValue ?
                new ObjectParameter("idKhachHang", idKhachHang) :
                new ObjectParameter("idKhachHang", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaDatMon", idDatMonParameter, idBanAnParameter, idMonAnParameter, idKhachHangParameter, soLuongParameter);
        }
    
        public virtual int sp_SuaHoaDon(Nullable<int> idHoaDon, Nullable<int> idKhachHang, Nullable<int> tien, Nullable<int> idKhuyenMai, string thongTin, Nullable<System.DateTime> ngayThanhToan)
        {
            var idHoaDonParameter = idHoaDon.HasValue ?
                new ObjectParameter("idHoaDon", idHoaDon) :
                new ObjectParameter("idHoaDon", typeof(int));
    
            var idKhachHangParameter = idKhachHang.HasValue ?
                new ObjectParameter("idKhachHang", idKhachHang) :
                new ObjectParameter("idKhachHang", typeof(int));
    
            var tienParameter = tien.HasValue ?
                new ObjectParameter("Tien", tien) :
                new ObjectParameter("Tien", typeof(int));
    
            var idKhuyenMaiParameter = idKhuyenMai.HasValue ?
                new ObjectParameter("idKhuyenMai", idKhuyenMai) :
                new ObjectParameter("idKhuyenMai", typeof(int));
    
            var thongTinParameter = thongTin != null ?
                new ObjectParameter("ThongTin", thongTin) :
                new ObjectParameter("ThongTin", typeof(string));
    
            var ngayThanhToanParameter = ngayThanhToan.HasValue ?
                new ObjectParameter("NgayThanhToan", ngayThanhToan) :
                new ObjectParameter("NgayThanhToan", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaHoaDon", idHoaDonParameter, idKhachHangParameter, tienParameter, idKhuyenMaiParameter, thongTinParameter, ngayThanhToanParameter);
        }
    
        public virtual int sp_SuaKhachHang(Nullable<int> idKhachHang, string hoTen, string gioiTinh, Nullable<System.DateTime> ngaySinh, string soDienThoai, string cMND)
        {
            var idKhachHangParameter = idKhachHang.HasValue ?
                new ObjectParameter("idKhachHang", idKhachHang) :
                new ObjectParameter("idKhachHang", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaKhachHang", idKhachHangParameter, hoTenParameter, gioiTinhParameter, ngaySinhParameter, soDienThoaiParameter, cMNDParameter);
        }
    
        public virtual int sp_SuaMonAn(Nullable<int> idMonAn, string tenMonAn, Nullable<int> giaTien, Nullable<int> idDanhMuc)
        {
            var idMonAnParameter = idMonAn.HasValue ?
                new ObjectParameter("idMonAn", idMonAn) :
                new ObjectParameter("idMonAn", typeof(int));
    
            var tenMonAnParameter = tenMonAn != null ?
                new ObjectParameter("TenMonAn", tenMonAn) :
                new ObjectParameter("TenMonAn", typeof(string));
    
            var giaTienParameter = giaTien.HasValue ?
                new ObjectParameter("GiaTien", giaTien) :
                new ObjectParameter("GiaTien", typeof(int));
    
            var idDanhMucParameter = idDanhMuc.HasValue ?
                new ObjectParameter("idDanhMuc", idDanhMuc) :
                new ObjectParameter("idDanhMuc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaMonAn", idMonAnParameter, tenMonAnParameter, giaTienParameter, idDanhMucParameter);
        }
    
        public virtual int sp_SuaNguyenLieu(Nullable<int> idNguyenLieu, string tenNguyenLieu, Nullable<int> soLuong, string dVTinh)
        {
            var idNguyenLieuParameter = idNguyenLieu.HasValue ?
                new ObjectParameter("idNguyenLieu", idNguyenLieu) :
                new ObjectParameter("idNguyenLieu", typeof(int));
    
            var tenNguyenLieuParameter = tenNguyenLieu != null ?
                new ObjectParameter("TenNguyenLieu", tenNguyenLieu) :
                new ObjectParameter("TenNguyenLieu", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var dVTinhParameter = dVTinh != null ?
                new ObjectParameter("DVTinh", dVTinh) :
                new ObjectParameter("DVTinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaNguyenLieu", idNguyenLieuParameter, tenNguyenLieuParameter, soLuongParameter, dVTinhParameter);
        }
    
        public virtual int sp_SuaNhanVien(Nullable<int> idNhanVien, string hoTen, string gioiTinh, Nullable<System.DateTime> ngaySinh, Nullable<System.DateTime> ngayVaoLam, string soDienThoai, string diaChi, string cMND, string email, Nullable<int> luong, Nullable<int> idChucVu)
        {
            var idNhanVienParameter = idNhanVien.HasValue ?
                new ObjectParameter("idNhanVien", idNhanVien) :
                new ObjectParameter("idNhanVien", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var ngayVaoLamParameter = ngayVaoLam.HasValue ?
                new ObjectParameter("NgayVaoLam", ngayVaoLam) :
                new ObjectParameter("NgayVaoLam", typeof(System.DateTime));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(int));
    
            var idChucVuParameter = idChucVu.HasValue ?
                new ObjectParameter("idChucVu", idChucVu) :
                new ObjectParameter("idChucVu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaNhanVien", idNhanVienParameter, hoTenParameter, gioiTinhParameter, ngaySinhParameter, ngayVaoLamParameter, soDienThoaiParameter, diaChiParameter, cMNDParameter, emailParameter, luongParameter, idChucVuParameter);
        }
    
        public virtual int sp_SuaTaiKhoan(Nullable<int> idTaiKhoan, string tenDangNhap, string matKhau, Nullable<bool> isAdmin)
        {
            var idTaiKhoanParameter = idTaiKhoan.HasValue ?
                new ObjectParameter("idTaiKhoan", idTaiKhoan) :
                new ObjectParameter("idTaiKhoan", typeof(int));
    
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("IsAdmin", isAdmin) :
                new ObjectParameter("IsAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaTaiKhoan", idTaiKhoanParameter, tenDangNhapParameter, matKhauParameter, isAdminParameter);
        }
    
        public virtual int sp_ThemBanAn(Nullable<int> sTTBan, Nullable<bool> trangThai)
        {
            var sTTBanParameter = sTTBan.HasValue ?
                new ObjectParameter("STTBan", sTTBan) :
                new ObjectParameter("STTBan", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemBanAn", sTTBanParameter, trangThaiParameter);
        }
    
        public virtual int sp_ThemChiTietMonAn(Nullable<int> idMonAn, Nullable<int> idNguyenLieu, Nullable<int> soLuong, string donVi)
        {
            var idMonAnParameter = idMonAn.HasValue ?
                new ObjectParameter("idMonAn", idMonAn) :
                new ObjectParameter("idMonAn", typeof(int));
    
            var idNguyenLieuParameter = idNguyenLieu.HasValue ?
                new ObjectParameter("idNguyenLieu", idNguyenLieu) :
                new ObjectParameter("idNguyenLieu", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var donViParameter = donVi != null ?
                new ObjectParameter("DonVi", donVi) :
                new ObjectParameter("DonVi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemChiTietMonAn", idMonAnParameter, idNguyenLieuParameter, soLuongParameter, donViParameter);
        }
    
        public virtual int sp_ThemDanhMuc(string tenDanhMuc, string moTa)
        {
            var tenDanhMucParameter = tenDanhMuc != null ?
                new ObjectParameter("TenDanhMuc", tenDanhMuc) :
                new ObjectParameter("TenDanhMuc", typeof(string));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDanhMuc", tenDanhMucParameter, moTaParameter);
        }
    
        public virtual int sp_ThemDatMon(Nullable<int> idBanAn, Nullable<int> idMonAn, Nullable<int> idKhachHang, Nullable<int> soLuong)
        {
            var idBanAnParameter = idBanAn.HasValue ?
                new ObjectParameter("idBanAn", idBanAn) :
                new ObjectParameter("idBanAn", typeof(int));
    
            var idMonAnParameter = idMonAn.HasValue ?
                new ObjectParameter("idMonAn", idMonAn) :
                new ObjectParameter("idMonAn", typeof(int));
    
            var idKhachHangParameter = idKhachHang.HasValue ?
                new ObjectParameter("idKhachHang", idKhachHang) :
                new ObjectParameter("idKhachHang", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDatMon", idBanAnParameter, idMonAnParameter, idKhachHangParameter, soLuongParameter);
        }
    
        public virtual int sp_ThemHoaDon(Nullable<int> idKhachHang, Nullable<int> tien, Nullable<int> idKhuyenMai, string thongTin, Nullable<System.DateTime> ngayThanhToan)
        {
            var idKhachHangParameter = idKhachHang.HasValue ?
                new ObjectParameter("idKhachHang", idKhachHang) :
                new ObjectParameter("idKhachHang", typeof(int));
    
            var tienParameter = tien.HasValue ?
                new ObjectParameter("Tien", tien) :
                new ObjectParameter("Tien", typeof(int));
    
            var idKhuyenMaiParameter = idKhuyenMai.HasValue ?
                new ObjectParameter("idKhuyenMai", idKhuyenMai) :
                new ObjectParameter("idKhuyenMai", typeof(int));
    
            var thongTinParameter = thongTin != null ?
                new ObjectParameter("ThongTin", thongTin) :
                new ObjectParameter("ThongTin", typeof(string));
    
            var ngayThanhToanParameter = ngayThanhToan.HasValue ?
                new ObjectParameter("NgayThanhToan", ngayThanhToan) :
                new ObjectParameter("NgayThanhToan", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemHoaDon", idKhachHangParameter, tienParameter, idKhuyenMaiParameter, thongTinParameter, ngayThanhToanParameter);
        }
    
        public virtual int sp_ThemKhachHang(string hoTen, string gioiTinh, Nullable<System.DateTime> ngaySinh, string soDienThoai, string cMND)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemKhachHang", hoTenParameter, gioiTinhParameter, ngaySinhParameter, soDienThoaiParameter, cMNDParameter);
        }
    
        public virtual int sp_ThemMonAn(string tenMonAn, Nullable<int> giaTien, string idDanhMuc)
        {
            var tenMonAnParameter = tenMonAn != null ?
                new ObjectParameter("TenMonAn", tenMonAn) :
                new ObjectParameter("TenMonAn", typeof(string));
    
            var giaTienParameter = giaTien.HasValue ?
                new ObjectParameter("GiaTien", giaTien) :
                new ObjectParameter("GiaTien", typeof(int));
    
            var idDanhMucParameter = idDanhMuc != null ?
                new ObjectParameter("idDanhMuc", idDanhMuc) :
                new ObjectParameter("idDanhMuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemMonAn", tenMonAnParameter, giaTienParameter, idDanhMucParameter);
        }
    
        public virtual int sp_ThemNguyenLieu(string tenNguyenLieu, Nullable<int> soLuong, string donViTinh)
        {
            var tenNguyenLieuParameter = tenNguyenLieu != null ?
                new ObjectParameter("TenNguyenLieu", tenNguyenLieu) :
                new ObjectParameter("TenNguyenLieu", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var donViTinhParameter = donViTinh != null ?
                new ObjectParameter("DonViTinh", donViTinh) :
                new ObjectParameter("DonViTinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNguyenLieu", tenNguyenLieuParameter, soLuongParameter, donViTinhParameter);
        }
    
        public virtual int sp_ThemNhanVien(string hoTen, string gioiTinh, Nullable<System.DateTime> ngaySinh, Nullable<System.DateTime> ngayVaoLam, string soDienThoai, string diaChi, string cMND, string email, Nullable<int> luong, Nullable<int> idChucVu)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var ngayVaoLamParameter = ngayVaoLam.HasValue ?
                new ObjectParameter("NgayVaoLam", ngayVaoLam) :
                new ObjectParameter("NgayVaoLam", typeof(System.DateTime));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(int));
    
            var idChucVuParameter = idChucVu.HasValue ?
                new ObjectParameter("idChucVu", idChucVu) :
                new ObjectParameter("idChucVu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhanVien", hoTenParameter, gioiTinhParameter, ngaySinhParameter, ngayVaoLamParameter, soDienThoaiParameter, diaChiParameter, cMNDParameter, emailParameter, luongParameter, idChucVuParameter);
        }
    
        public virtual int sp_ThemTaiKhoan(string tenDangNhap, string matKhau, Nullable<bool> isAdmin)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("IsAdmin", isAdmin) :
                new ObjectParameter("IsAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemTaiKhoan", tenDangNhapParameter, matKhauParameter, isAdminParameter);
        }
    
        public virtual int sp_TinhTien(Nullable<int> idDatMon, Nullable<int> idKhuyenMai, string thongTin)
        {
            var idDatMonParameter = idDatMon.HasValue ?
                new ObjectParameter("idDatMon", idDatMon) :
                new ObjectParameter("idDatMon", typeof(int));
    
            var idKhuyenMaiParameter = idKhuyenMai.HasValue ?
                new ObjectParameter("idKhuyenMai", idKhuyenMai) :
                new ObjectParameter("idKhuyenMai", typeof(int));
    
            var thongTinParameter = thongTin != null ?
                new ObjectParameter("thongTin", thongTin) :
                new ObjectParameter("thongTin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TinhTien", idDatMonParameter, idKhuyenMaiParameter, thongTinParameter);
        }
    
        public virtual int sp_XoaChiTietMonAn(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaChiTietMonAn", idParameter);
        }
    
        public virtual int sp_XoaDanhMuc(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaDanhMuc", idParameter);
        }
    
        public virtual int sp_XoaDatMon(Nullable<int> idDatMon)
        {
            var idDatMonParameter = idDatMon.HasValue ?
                new ObjectParameter("idDatMon", idDatMon) :
                new ObjectParameter("idDatMon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaDatMon", idDatMonParameter);
        }
    
        public virtual int sp_XoaHoaDon(Nullable<int> idHoaDon)
        {
            var idHoaDonParameter = idHoaDon.HasValue ?
                new ObjectParameter("idHoaDon", idHoaDon) :
                new ObjectParameter("idHoaDon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaHoaDon", idHoaDonParameter);
        }
    
        public virtual int sp_XoaKhachHang(Nullable<int> idKhachHang)
        {
            var idKhachHangParameter = idKhachHang.HasValue ?
                new ObjectParameter("idKhachHang", idKhachHang) :
                new ObjectParameter("idKhachHang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaKhachHang", idKhachHangParameter);
        }
    
        public virtual int sp_XoaMonAn(Nullable<int> idMonAn)
        {
            var idMonAnParameter = idMonAn.HasValue ?
                new ObjectParameter("idMonAn", idMonAn) :
                new ObjectParameter("idMonAn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaMonAn", idMonAnParameter);
        }
    
        public virtual int sp_XoaMotBanAn(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaMotBanAn", idParameter);
        }
    
        public virtual int sp_XoaNguyenLieu(Nullable<int> idNguyenLieu)
        {
            var idNguyenLieuParameter = idNguyenLieu.HasValue ?
                new ObjectParameter("idNguyenLieu", idNguyenLieu) :
                new ObjectParameter("idNguyenLieu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaNguyenLieu", idNguyenLieuParameter);
        }
    
        public virtual int sp_XoaNhanVien(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaNhanVien", idParameter);
        }
    
        public virtual int sp_XoaTaiKhoan(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaTaiKhoan", idParameter);
        }
    
        public virtual int upstp_TrangThaiBan(Nullable<int> ban, Nullable<bool> trangthai)
        {
            var banParameter = ban.HasValue ?
                new ObjectParameter("ban", ban) :
                new ObjectParameter("ban", typeof(int));
    
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upstp_TrangThaiBan", banParameter, trangthaiParameter);
        }
    }
}
